# Generated by Django 3.1.5 on 2021-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('gearbox', models.PositiveSmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], default='1', verbose_name='Трансмиссия')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
            ],
        ),
    ]
